Repository AY2122S1-CS2113T-W13-3/tp, pull requests merged in 2021-11, with the labels that each got.

#142 Add JavaDocs for code implemented by Amos
  src/main/java/seedu/duke/command/ListCommand.java
  src/main/java/seedu/duke/command/SortCommand.java
  src/main/java/seedu/duke/command/flags/ListFlag.java
  src/main/java/seedu/duke/command/flags/SortFlag.java
  src/main/java/seedu/duke/parser/CommandParser.java
  src/main/java/seedu/duke/task/taskmanager/TaskManager.java
  src/main/java/seedu/duke/ui/Ui.java
  src/test/java/seedu/duke/parser/CommandParserTest.java
  src/test/java/seedu/duke/task/TaskManagerTest.java
  text-ui-test/EXPECTED.TXT
Labels: type.Task, priority.High

#147 Branch update UI
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/ui/Ui.java
  src/test/java/seedu/duke/DukeTest.java
Labels: type.Enhancement, type.Task, priority.Low

#149 General Update to Developer Guide
  docs/DeveloperGuide.md
  docs/images/Amos UML Diagrams/Architecture - SchedUrMods.png
  docs/images/Amos UML Diagrams/Sequence Diagram - Input Valid Command.png
Labels: type.Enhancement, type.Task, priority.High

#150 Fix DG image issue
  docs/DeveloperGuide.md
  docs/images/Amos UML Diagrams/Sequence Diagram - Input Valid Command.png
  docs/images/AmosUMLDiagrams/Architecture.png
  docs/images/AmosUMLDiagrams/SD_ValidInput.png
Labels: type.Bug, priority.Medium

#135 Implement link feature
  src/main/java/seedu/duke/command/BrowseCommand.java
  src/main/java/seedu/duke/command/CommandEnum.java
  src/main/java/seedu/duke/command/EditCommand.java
  src/main/java/seedu/duke/command/flags/LessonFlag.java
  src/main/java/seedu/duke/exception/BrowseFailException.java
  src/main/java/seedu/duke/parser/CommandParser.java
  src/main/java/seedu/duke/task/Task.java
  src/main/java/seedu/duke/task/taskmanager/TaskManager.java
  src/main/java/seedu/duke/task/type/Event.java
  src/main/java/seedu/duke/task/type/Lesson.java
  src/main/java/seedu/duke/utility/ExternalHelper.java
Labels: type.Epic, type.Enhancement, type.Task, priority.High

#155 Branch update dg part2
  docs/DeveloperGuide.md
  docs/images/AmosUMLDiagrams/CD_ParserComponent.drawio.png
  docs/images/AmosUMLDiagrams/CD_UIComponent.png
  src/main/java/seedu/duke/Duke.java
Labels: type.Task, priority.High

#153 Fix NullPointerException
  src/main/java/seedu/duke/command/BrowseCommand.java
Labels: type.Bug, priority.High, severity.High

#154 Add usage for module and browse commands
  src/main/java/seedu/duke/command/BrowseCommand.java
  src/main/java/seedu/duke/command/HelpCommand.java
Labels: type.Enhancement, priority.Medium

#156 update all help command messages for all commands for better clarity
  src/main/java/seedu/duke/command/BrowseCommand.java
  src/main/java/seedu/duke/command/ByeCommand.java
  src/main/java/seedu/duke/command/DeleteCommand.java
  src/main/java/seedu/duke/command/EditCommand.java
  src/main/java/seedu/duke/command/HelpCommand.java
  src/main/java/seedu/duke/command/ListCommand.java
  src/main/java/seedu/duke/command/ReminderCommand.java
  src/main/java/seedu/duke/command/SortCommand.java
  src/main/java/seedu/duke/command/addtask/DeadlineCommand.java
  src/main/java/seedu/duke/command/addtask/EventCommand.java
  src/main/java/seedu/duke/command/addtask/ModuleCommand.java
  src/main/java/seedu/duke/command/addtask/TodoCommand.java
Labels: type.Task, priority.Low

#157 rename class diagram for Parser Component
  docs/images/AmosUMLDiagrams/CD_ParserComponent.png
Labels: type.Bug, priority.Low

#159 Branch update ug
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/README.md
  docs/UserGuide.md
Labels: type.Enhancement, type.Task, priority.Medium

#160 add sequence diagram for "Filtering the tasklist"
  docs/DeveloperGuide.md
  docs/images/AmosUMLDiagrams/SD_FilteringTasklist.png
Labels: type.Enhancement, type.Task, priority.Medium

#162 add JavaDocs for exception classes
  src/main/java/seedu/duke/exception/EmptySortCriteriaException.java
  src/main/java/seedu/duke/exception/InvalidTaskTypeException.java
  src/main/java/seedu/duke/exception/ListFormatException.java
  src/main/java/seedu/duke/exception/MissingFilterArgumentException.java
  src/main/java/seedu/duke/exception/SortFormatException.java
  src/main/java/seedu/duke/exception/TaskIsNonRecurringException.java
Labels: type.Enhancement, type.Task, priority.Medium

#167 Branch apzh ppp
  docs/team/apzh.md
Labels: type.Task, priority.High

#168 Fix PPP image issues for APZH
  docs/AboutUs.md
  docs/team/apzh.md
Labels: type.Task, priority.Low

#175 fix broken PPP link in AboutUs.md
  docs/AboutUs.md
Labels: type.Task, priority.High

#176 fix image not displaying bug in PPP
  docs/team/apzh.md
Labels: type.Bug

#181 Implement upcoming command
  build.gradle
  src/main/java/seedu/tp/command/CommandEnum.java
  src/main/java/seedu/tp/command/UpcomingCommand.java
  src/main/java/seedu/tp/parser/CommandParser.java
  src/main/java/seedu/tp/task/Task.java
  src/main/java/seedu/tp/task/taskmanager/TaskManager.java
  src/main/java/seedu/tp/task/type/Deadline.java
  src/main/java/seedu/tp/task/type/Event.java
  src/main/java/seedu/tp/task/type/Lesson.java
  src/main/java/seedu/tp/task/type/Todo.java
Labels: type.Story, type.Task, priority.Medium

#184 improved clarity of PPP and added PRs for DG and UG updates for APZH
  docs/team/apzh.md
Labels: type.Task, priority.Medium

#185 fix minor bug with PPP
  docs/team/apzh.md
Labels: type.Bug, severity.Low

#183 Add has link indicator to Lesson description
  src/main/java/seedu/tp/command/BrowseCommand.java
  src/main/java/seedu/tp/exception/NoLinkException.java
  src/main/java/seedu/tp/task/type/Lesson.java
Labels: type.Enhancement, priority.Medium, severity.Medium

#186 Add UG, DG and JavaDoc for Mods parts
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/tp/command/BrowseCommand.java
  src/main/java/seedu/tp/command/addtask/ModuleCommand.java
  src/main/java/seedu/tp/command/flags/LessonFlag.java
  src/main/java/seedu/tp/exception/BrowseFailException.java
  src/main/java/seedu/tp/exception/ImpossibleError.java
  src/main/java/seedu/tp/exception/LessonNotFoundException.java
  src/main/java/seedu/tp/nusmods/NusModsParser.java
  src/main/java/seedu/tp/nusmods/Semester.java
  src/main/java/seedu/tp/task/type/Lesson.java
Labels: type.Enhancement, priority.High, severity.Medium

#188 update PPP quality
  docs/team/apzh.md
Labels: type.Task, priority.Low, severity.VeryLow

#190 Print friendly message if no upcoming tasks
  src/main/java/seedu/tp/command/UpcomingCommand.java
Labels: type.Enhancement, severity.VeryLow

#189 Amend command summary for module and browse
  docs/UserGuide.md
Labels: type.Enhancement, priority.Medium, severity.Medium

#192 Add priority indicator for lesson description
  src/main/java/seedu/tp/task/type/Lesson.java
Labels: type.Enhancement, priority.Medium, severity.VeryLow

#193 Check module-class pair exists and error if not
  src/main/java/seedu/tp/command/addtask/ModuleCommand.java
  src/main/java/seedu/tp/exception/NoSuchModuleException.java
  src/main/java/seedu/tp/nusmods/NusModsParser.java
  src/test/java/seedu/tp/nusmods/NusModsParserTest.java
Labels: type.Enhancement, priority.Medium, severity.Medium

#195 tweak task description of Lesson objects + minor quality adjustments to UG
  docs/UserGuide.md
  src/main/java/seedu/tp/task/type/Lesson.java
Labels: type.Enhancement, type.Task, priority.Low

#196 fix conversion to PDF format for PPP
  docs/team/apzh.md
Labels: type.Enhancement, priority.Low, severity.Low

#197 remove space between author tags and methods in Command Parser class
  src/main/java/seedu/tp/parser/CommandParser.java
Labels: type.Bug, priority.Medium, severity.Medium

#205 Add class diagram for NusModsParser and Semester
  docs/DeveloperGuide.md
  docs/images/JialunUMLDiagrams/CD_NusModsParser.png
  docs/images/JialunUMLDiagrams/CD_Semester.png
Labels: type.Enhancement, priority.Medium, severity.Medium

#207 Add friendly message if the browsed task is not a lesson
  src/main/java/seedu/tp/command/BrowseCommand.java
  src/main/java/seedu/tp/exception/NotALessonException.java
Labels: type.Enhancement, priority.Medium, severity.Low

#208 Amend instructions for zip releases
  docs/UserGuide.md
Labels: type.Bug, priority.High, severity.Low
